- name: 'Job detail pages'
  uriPattern: '{node}/id/{jobid}<defaultUriSuffix>'
  defaults:
    '@package': 'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@action': 'show'
    '@format': 'html'
  routeParts:
    node:
      handler: Neos\Neos\Routing\FrontendNodeRoutePartHandlerInterface
      options:
        nodeType: 'Shel.Neos.Coveto:Document.JobDetails'
  appendExceedingArguments: true
